apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-certs-volume-claim
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.clusterIP }}
    path: "/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: public-certs-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi